package mcp

import (
	"net/url"
	"regexp"
	"strings"
)

// claudeCredential is whether the variable name, holding value, stays empty
// in a remote server's URL and headers, so that no declaration carries it to
// a third party. The rules are those of Claude Code 2.1.278, which does not
// publish them: a name matches without regard to case and with an INPUT_
// prefix, and a *_BASE_URL matches when its value embeds credentials.
// Beyond them, every ANTHROPIC_ and CLAUDE_ variable matches, so that a
// credential a later Claude Code protects under those prefixes stays
// withheld while this list lags behind.
func claudeCredential(name, value string) bool {
	n := strings.TrimPrefix(strings.ToUpper(name), "INPUT_")
	if strings.HasPrefix(n, "ANTHROPIC_") || strings.HasPrefix(n, "CLAUDE_") ||
		claudeCredentials[n] || claudeCredentialPattern.MatchString(n) {
		return true
	}
	if strings.HasSuffix(n, "_BASE_URL") {
		u, err := url.Parse(value)
		return err == nil && u.User != nil
	}
	return false
}

var claudeCredentialPattern = regexp.MustCompile(`^(OTEL_.*|GIT_CONFIG_PARAMETERS|GIT_CONFIG_(KEY|VALUE)_[0-9]+|CARGO_REGISTRIES_.+_TOKEN|POETRY_HTTP_BASIC_.+|POETRY_PYPI_TOKEN_.+|CONAN_LOGIN_USERNAME_.+|CONAN_PASSWORD_.+|BUNDLE_.+__.+|ORG_GRADLE_PROJECT_.+)$`)

var claudeCredentials = func() map[string]bool {
	names := map[string]bool{}
	for _, n := range strings.Fields(`
		AGENT_PROXY_AUTH_TOKEN
		AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_BEARER_TOKEN_BEDROCK AWS_WEB_IDENTITY_TOKEN_FILE
		AWS_CONTAINER_CREDENTIALS_RELATIVE_URI AWS_CONTAINER_CREDENTIALS_FULL_URI
		AWS_CONTAINER_AUTHORIZATION_TOKEN AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE
		GOOGLE_APPLICATION_CREDENTIALS GOOGLE_GHA_CREDS_PATH CLOUDSDK_AUTH_ACCESS_TOKEN
		CLOUDSDK_AUTH_ACCESS_TOKEN_FILE CLOUDSDK_AUTH_AUTHORIZATION_TOKEN_FILE GOOGLE_OAUTH_ACCESS_TOKEN
		AZURE_CLIENT_SECRET IDENTITY_HEADER MSI_SECRET AZURE_CLIENT_CERTIFICATE_PATH
		AZURE_CLIENT_CERTIFICATE_PASSWORD AZURE_PASSWORD AZURE_FEDERATED_TOKEN_FILE AZURE_AUTH_LOCATION
		NODE_AUTH_TOKEN NUGET_AUTH_TOKEN CARGO_REGISTRY_TOKEN TWINE_PASSWORD TWINE_USERNAME
		PYPI_TOKEN PYPI_API_TOKEN UV_PUBLISH_TOKEN UV_PUBLISH_PASSWORD UV_PUBLISH_USERNAME
		FLIT_PASSWORD FLIT_USERNAME HATCH_INDEX_AUTH HATCH_INDEX_USER GEM_HOST_API_KEY
		MATURIN_PYPI_TOKEN MATURIN_PASSWORD MATURIN_USERNAME CONAN_LOGIN_USERNAME CONAN_PASSWORD
		ANACONDA_API_TOKEN BINSTAR_API_TOKEN
		NPM_TOKEN CODEARTIFACT_AUTH_TOKEN PIP_INDEX_URL PIP_EXTRA_INDEX_URL UV_INDEX_URL
		UV_EXTRA_INDEX_URL UV_DEFAULT_INDEX UV_INDEX GOPROXY GOAUTH HTTPS_PROXY HTTP_PROXY ALL_PROXY
		VAULT_TOKEN VAULT_AUTH_TOKEN VAULT_ROLE_ID VAULT_SECRET_ID CONSUL_HTTP_TOKEN CONSUL_HTTP_AUTH
		NOMAD_TOKEN NOMAD_HTTP_AUTH
		CI_REGISTRY_USER CI_DEPLOY_USER JF_USER FASTLANE_SESSION MATCH_GIT_BASIC_AUTHORIZATION
		SONAR_TOKEN SONARQUBE_SCANNER_PARAMS SONAR_SCANNER_JSON_PARAMS
		SLACK_WEBHOOK SLACK_WEBHOOK_URL DISCORD_WEBHOOK DISCORD_WEBHOOK_URL TEAMS_WEBHOOK_URL MS_TEAMS_WEBHOOK_URI
		ACTIONS_ID_TOKEN_REQUEST_TOKEN ACTIONS_ID_TOKEN_REQUEST_URL ACTIONS_RUNTIME_TOKEN ACTIONS_RUNTIME_URL
		ALL_INPUTS VSS_NUGET_EXTERNAL_FEED_ENDPOINTS ARTIFACTS_CREDENTIALPROVIDER_EXTERNAL_FEED_ENDPOINTS
		VSS_NUGET_ACCESSTOKEN ARTIFACTS_CREDENTIALPROVIDER_ACCESSTOKEN
		COMPOSER_AUTH OVERRIDE_GITHUB_TOKEN DEFAULT_WORKFLOW_TOKEN SSH_SIGNING_KEY
		MCP_CLIENT_SECRET MCP_XAA_IDP_CLIENT_SECRET ENVIRONMENT_SERVICE_KEY
		SELF_HOSTED_RUNNER_POOL_SECRET SELF_HOSTED_RUNNER_ENVIRONMENT_SECRET
	`) {
		names[n] = true
	}
	return names
}()
